### ISSUE TITLE
add mypy for type check?

### ISSUE THREAD

**Issue by asukaminato0721** [fsspec/opendalfs#3]
https://github.com/fsspec/opendalfs/blob/459710ced41c935c5fc9d335f785e446134e6e78/.github/workflows/ci.yml#L32-L37

https://github.com/python/mypy?tab=readme-ov-file#quick-start

**Comment by Xuanwo** [comment]
Hello, based on what I understand, the Python code in this repository appears to be a simple wrapper such as `__all__ = _opendalfs.__all__`. At this stage, type checking is unnecessary.

**Comment by Xuanwo** [comment]
I'm going to close this issue now. Feel free to reopen it if you still have questions.
